name: Pull Request Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DIRECT_URL: ${{ secrets.DIRECT_URL }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm install
          npm ci
        
      - name: Create environment files
        run: |
          # Create .env.local
          echo "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" > .env.local
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" >> .env.local
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env.local
          echo "DIRECT_URL=${{ secrets.DIRECT_URL }}" >> .env.local
          
          # Create .env.production
          cp .env.local .env.production
          
          # Create .env file (used during the build process)
          cp .env.local .env
          
          # Create .env.development
          cp .env.local .env.development
          
          # Print contents for debugging
          echo "Environment files created:"
          ls -la .env*
          
          echo "Contents of .env file:"
          cat .env
          
      - name: Run tests
        run: npm test
        
      - name: Build project
        run: npm run build
        
      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo, number } = context.issue;
            
            // Check workflow outcome from previous steps
            const outcome = process.env.WORKFLOW_OUTCOME || 'success';
            
            if (outcome !== 'success') {
              github.rest.issues.createComment({
                owner,
                repo,
                issue_number: number,
                body: `## PR Check Results
                
                Some checks didn't pass. Please review the workflow results for details.
                
                > This is an automated comment from the PR check workflow.`
              });
            } else {
              github.rest.issues.createComment({
                owner,
                repo,
                issue_number: number,
                body: `## PR Check Results
                
                ✅ All checks passed successfully!
                
                > This is an automated comment from the PR check workflow.`
              });
            } 