name: Pull Request Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Lint check
        run: npm run lint || echo "Linting has issues"
        
      - name: Build project
        run: npm run build
        
      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo, number } = context.issue;
            
            // Check workflow outcome from previous steps
            const outcome = process.env.WORKFLOW_OUTCOME || 'success';
            
            if (outcome !== 'success') {
              github.rest.issues.createComment({
                owner,
                repo,
                issue_number: number,
                body: `## PR Check Results
                
                Some checks didn't pass. Please review the workflow results for details.
                
                > This is an automated comment from the PR check workflow.`
              });
            } else {
              github.rest.issues.createComment({
                owner,
                repo,
                issue_number: number,
                body: `## PR Check Results
                
                ✅ All checks passed successfully!
                
                > This is an automated comment from the PR check workflow.`
              });
            } 